___

<a href='http://www.pieriandata.com'> <img src='./Pierian_Data_Logo.png' /></a>
___

# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [1]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [5]:
my_list = [1,2,3]
my_list2 = [1,2,3, "hh"]
print(my_list)
print(my_list2)

[1, 2, 3]
[1, 2, 3, 'hh']


In [7]:
print(np.array(my_list)) #we can cast 'my_list' as an array (1D array or vector in this case). so we can cast a normal Python list into an array.
print(np.array(my_list2))

[1 2 3]
['1' '2' '3' 'hh']


In [8]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]] #we can cast 'a list of lists' as a 2D array or matrix.
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_matrix) #we can 'my_matrix' to a 2D array.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [18]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [15]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
list(range(0,11,2))

[0, 2, 4, 6, 8, 10]

In [110]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [24]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [26]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [27]:
np.ones(3) #we can pass a single number for a 1D array or a tuple of them for 2 or more D array (matrices)

array([ 1.,  1.,  1.])

In [28]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [26]:
np.linspace(0,10,3) #returns a 1D array (vector)

array([ 0.,  5., 10.])

In [25]:
np.linspace(0,10) #returns a 1D array (vector)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [27]:
np.linspace(0,10,50) #returns a 1D array (vector)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates an identity matrix

In [37]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [31]:
np.random.rand(2) #shape = (2,) a 1D array of random nums uniformly distributed from 0 to 1
#This is gonna create an array of the given shape you pass in and 
# it's gonna populate it with random samples from a uniform distribution over 0 to 1. 

array([0.42078768, 0.29797576])

In [37]:
np.random.rand(5,5)

array([[0.94304382, 0.6033384 , 0.63042769, 0.94902426, 0.32947279],
       [0.08160163, 0.29057026, 0.96229376, 0.1982602 , 0.69976649],
       [0.86912178, 0.31943334, 0.10186856, 0.35970981, 0.07115412],
       [0.33723619, 0.38312974, 0.15998397, 0.83377019, 0.72152118],
       [0.74579907, 0.75889121, 0.13584201, 0.70847084, 0.83386378]])

### randn

Return a sample (or samples) from the "standard normal" (Gaussian) distribution. Unlike rand which is uniform:

In [91]:
np.random.randn(2) #Generates random numbers from a standard normal distribution centered around zero(mean (μ)= 0, standard deviation (σ) = 1).

array([-0.38528645,  2.05522612])

In [45]:
np.random.randn(5,5)

array([[ 0.70154515,  0.22441999,  1.33563186,  0.82872577, -0.28247509],
       [ 0.64489788,  0.61815094, -0.81693168, -0.30102424, -0.29030574],
       [ 0.8695976 ,  0.413755  ,  2.20047208,  0.17955692, -0.82159344],
       [ 0.59264235,  1.29869894, -1.18870241,  0.11590888, -0.09181687],
       [-0.96924265, -1.62888685, -2.05787102, -0.29705576,  0.68915542]])

## `np.random.rand(2)` vs `np.random.randn(2)`

### 1. **`np.random.rand(2)`**
- Generates **random numbers from a uniform distribution** in the range **[0, 1)**.
- Returns an array of shape `(2,)`, where each number is sampled independently.
- Example:

    ```python
    import numpy as np
    np.random.rand(2)
    ```
    
    **Output (example, will vary each time):**
    
    ```python
    array([0.3745, 0.9572])  # Random numbers between 0 and 1
    ```

### 2. **`np.random.randn(2)`**
- Generates **random numbers from a standard normal distribution** (mean (μ)= 0, standard deviation (σ) = 1).
- Returns an array of shape `(2,)`, where each number follows a normal (Gaussian) distribution.
- Example:

    ```python
    np.random.randn(2)
    ```
    
    **Output (example, will vary each time):**
    
    ```python
    array([-1.023, 0.532])  # Random numbers with mean 0 and std dev 1
    ```
# Probability Distributions

## 1. Uniform Distribution
**Definition:** Every value in a given range has an equal probability of occurring.

**Shape:** A flat, rectangular shape.

### Key Characteristics:
- All values between a minimum and maximum are equally likely.
- It has a constant **probability density function (PDF)**.
- **Two main types:**
  - **Continuous Uniform Distribution** (e.g., `np.random.rand()`) → Values are spread evenly across an interval (e.g., [0, 1)).
  - **Discrete Uniform Distribution** → Only certain values are possible (e.g., rolling a fair die, where each face has an equal 1/6 chance).

### Uniform Distribution Example
```python
import numpy as np

# 5 random numbers between 0 and 10
np.random.uniform(0, 10, 5)   #Possible Output:[1.5, 6.8, 9.2, 3.3, 5.4]
```
---

## 2. Normal (Gaussian) Distribution
**Definition:** A bell-shaped distribution where values are more likely to be near the mean (average) and less likely as they move further from the mean.

**Shape:** A symmetric bell curve.

### Key Characteristics:
- Defined by **mean (μ)** and **standard deviation (σ)**.
- **68%-95%-99.7% Rule:**
  - 68% of data lies within **1σ** of the mean.
  - 95% within **2σ**.
  - 99.7% within **3σ**.
- Many natural phenomena (e.g., height, IQ scores, measurement errors) follow a **normal distribution**.
## Understanding `np.random.randn(2)`

- `np.random.randn(2)` generates numbers from a **standard normal distribution** (mean = **0**, standard deviation = **1**).
- In a normal distribution, about **99.7%** of values fall within **±3 standard deviations** (i.e., between -3 and 3).
- Values greater than **3 standard deviations** (**3σ**) from the mean are **almost impossible** to occur.

### Uniform Distribution Example
```python
import numpy as np

# 5 random numbers from a normal distribution with mean 0 and standard deviation 1
np.random.normal(0, 1, 5)  #Possible Output:[0.35, -1.2, 1.7, -0.45, 0.8]
```

### 📌 Summary of Differences:

| Function | Distribution | Range |
|----------|-------------|-------|
| `np.random.rand(n)` | Uniform | \[0, 1) |
| `np.random.randn(n)` | Standard Normal (Gaussian) | (-∞, ∞) |

🔹 Use **`rand()`** if you need **random values between 0 and 1**.  
🔹 Use **`randn()`** if you need **values following a normal distribution**.


## 📊 Uniform vs Normal Distribution

| Feature               | Uniform Distribution            | Normal Distribution          |
|-----------------------|--------------------------------|-----------------------------|
| **Shape**            | Rectangular (flat)            | Bell-shaped (Gaussian)      |
| **Probability**      | Equal for all values          | Higher near the mean, lower at extremes |
| **Parameters**       | Min & Max (`a`, `b`)          | Mean (μ), Standard Deviation (σ) |
| **Example Use**      | Random sampling, simulation   | Heights, test scores, stock prices |
| **Example Function** | `np.random.uniform()`         | `np.random.normal()`        |

🔹 **Uniform Distribution:** Used when each outcome has an **equal probability**.  
🔹 **Normal Distribution:** Used when values cluster around a **mean (μ)** with variation.


### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [66]:
np.random.uniform(0, 100) 
#generates a random floating-point number from a uniform distribution between 0 (inclusive) and 100 (exclusive). The output is a decimal (e.g., 0.235, 99.8, 57.2, etc.).

42.57349327604093

In [105]:
np.random.randint(1,100) #generates a random integer from a uniform distribution.
#generates random integers between 1 (inclusive) and 100 (exclusive). The output is always a whole number (e.g., 1, 2, 3, ... 99).

72

In [39]:
np.random.randint(1,100,10)

array([60, 55, 81, 72, 14, 26, 53, 80, 52, 17])

## Array Attributes and Methods

Let's discuss some useful attributes and methods of an array:

In [ ]:
#creating two new array objects:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [118]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [57]:
ranarr

array([10, 12, 41, 17, 49,  2, 46,  3, 19, 39])

In [119]:
len(arr)

25

## Reshape
Returns an array containing the same data with a new shape.

In [116]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [120]:
ranarr

array([19, 12, 12, 18,  9,  7, 27, 39, 16, 31])

In [121]:
ranarr.max()

39

In [125]:
ranarr.argmax()

7

In [124]:
ranarr.min()

7

In [126]:
ranarr.argmin()

5

## Shape

Shape is an attribute that arrays have (not a method):

In [65]:
# Vector (n,) means 1D array with n elements.
arr.shape

(25,)

In [66]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [69]:
arr.reshape(1,25).shape

(1, 25)

In [70]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [76]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [75]:
arr.dtype

dtype('int64')

We've shown you how to create NumPy arrays either by casting a Python list to a NumPy array or by using one of the built-in functions for NumPy arrays; such as arange(), zeros(), ones(), linspace(), eye() , and also the random generation methods, you call np.random.rand/randn/randint or some of the other random methods

In [127]:
from numpy.random import randint

In [128]:
randint(2, 10) #Instead of writing np.random.randint(2, 10), we can write this, but first, we should write the line above.

4

# Great Job!