___

<a href='http://www.pieriandata.com'> <img src='./Pierian_Data_Logo.png' /></a>
___

# DataFrames

DataFrames are the workhorse of pandas and are directly inspired by the R programming language. We can think of a DataFrame as a bunch of Series objects put together to share the same index. Let's use pandas to explore this topic!

In [196]:
import pandas as pd
import numpy as np

In [197]:
# np.random.seed(101)
# np.random.randn(2)
#output: array([2.70684984, 0.62813271])

In [198]:
from numpy.random import randn #This imports the function randn() directly from numpy.random. It allows you to call randn() without prefixing it with np.random..
np.random.seed(101)
# randn generates samples from the standard normal distribution (mean = 0, std = 1).
# After this line, you can just call randn(...) without writing np.random.randn(...).
randn(2)

array([2.70684984, 0.62813271])

### **`np.random.randn(2)`**
- Generates **random numbers from a standard normal distribution** (mean (μ)= 0, standard deviation (σ) = 1).
- Returns an array of shape `(2,)`, where each number follows a normal (Gaussian) distribution.
### Understanding `np.random.randn(2)`

- `np.random.randn(2)` generates numbers from a **standard normal distribution** (mean = **0**, standard deviation = **1**).
- In a normal distribution, about **99.7%** of values fall within **±3 standard deviations** (i.e., between -3 and 3).
- Values greater than **3 standard deviations** (**3σ**) from the mean are **almost impossible** to occur.


In [199]:
df = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())

In [200]:
'A B C D E'.split()
# type('A B C D E'.split())     #list

['A', 'B', 'C', 'D', 'E']

In [201]:
df
#Each of its columns is actually just a Pandas Series.So 'W' is a Pandas Series and so forth.

W         X         Y         Z
A  0.907969  0.503826  0.651118 -0.319318
B -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872
D -0.933237  0.955057  0.190794  1.978757
E  2.605967  0.683509  0.302665  1.693723

In [202]:
pd.DataFrame(randn(5,4),index=tuple('ABCDE'),columns=tuple('WXYZ'))
#Both 'ABCDE' and 'WXYZ' are strings, but Pandas expects a list-like object (e.g. list or tuple) for the index and columns parameters.
#or
# pd.DataFrame(randn(5,4), tuple('ABCDE'), tuple('WXYZ'))

W         X         Y         Z
A -1.706086 -1.159119 -0.134841  0.390528
B  0.166905  0.184502  0.807706  0.072960
C  0.638787  0.329646 -0.497104 -0.754070
D -0.943406  0.484752 -0.116773  1.901755
E  0.238127  1.996652 -0.993263  0.196800

## Selection and Indexing

Let's learn the various methods to grab data from a DataFrame

In [203]:
# There are two different ways to grab a column from a DataFrame. The main way—and the one we should always use—is by using bracket notation and passing in the column name:
df['W']
# type(df['W']) pandas.core.series.Series

A    0.907969
B   -0.848077
C    0.528813
D   -0.933237
E    2.605967
Name: W, dtype: float64

In [204]:
# Pass a list of column names
df[['W','Z']]
#or
# df.loc[:,['W','Z']]
'''
❌ Why df[:, ['W', 'Z']] fails:
    Pandas raises an error because ':' is interpreted as a row indexer, and you're passing a list as the column indexer, without a proper interface (.loc, .iloc, etc.).
'''

"\n❌ Why df[:, ['W', 'Z']] fails:\n    Pandas raises an error because ':' is interpreted as a row indexer, and you're passing a list as the column indexer, without a proper interface (.loc, .iloc, etc.).\n"

In [205]:
# SQL Syntax (NOT RECOMMENDED!): table_name.column_name
df.W

A    0.907969
B   -0.848077
C    0.528813
D   -0.933237
E    2.605967
Name: W, dtype: float64

DataFrame Columns are just Series

In [206]:
type(df['W'])

pandas.core.series.Series

**Creating a new column:**

In [207]:
df['new'] = df['W'] + df['Y']

In [208]:
df

W         X         Y         Z       new
A  0.907969  0.503826  0.651118 -0.319318  1.559087
B -0.848077  0.605965 -2.018168  0.740122 -2.866245
C  0.528813 -0.589001  0.188695 -0.758872  0.717509
D -0.933237  0.955057  0.190794  1.978757 -0.742443
E  2.605967  0.683509  0.302665  1.693723  2.908633

**Removing Columns**

In [209]:
#By default '.drop()' doesn't happen in-place. I mean our actual DataFrame won't change after using this method unless we specifically specify this to occur in-place.
df.drop('A') #by default 'axis=0' for the 'drop' method which refers to the index. If we want to refer to the columns we need to specify 'axis=1'.
#or
# df.drop('A', axis = 0)
#df.drop('new')     #KeyError

W         X         Y         Z       new
B -0.848077  0.605965 -2.018168  0.740122 -2.866245
C  0.528813 -0.589001  0.188695 -0.758872  0.717509
D -0.933237  0.955057  0.190794  1.978757 -0.742443
E  2.605967  0.683509  0.302665  1.693723  2.908633

In [210]:
df.drop('new',axis=1)

W         X         Y         Z
A  0.907969  0.503826  0.651118 -0.319318
B -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872
D -0.933237  0.955057  0.190794  1.978757
E  2.605967  0.683509  0.302665  1.693723

In [211]:
# Not inplace unless specified!
df

W         X         Y         Z       new
A  0.907969  0.503826  0.651118 -0.319318  1.559087
B -0.848077  0.605965 -2.018168  0.740122 -2.866245
C  0.528813 -0.589001  0.188695 -0.758872  0.717509
D -0.933237  0.955057  0.190794  1.978757 -0.742443
E  2.605967  0.683509  0.302665  1.693723  2.908633

In [212]:
df.drop('new',axis=1,inplace=True)

In [213]:
df

W         X         Y         Z
A  0.907969  0.503826  0.651118 -0.319318
B -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872
D -0.933237  0.955057  0.190794  1.978757
E  2.605967  0.683509  0.302665  1.693723

Can also drop rows this way:

In [214]:
df.drop('E',axis=0)
#Or
#df.drop('E')

W         X         Y         Z
A  0.907969  0.503826  0.651118 -0.319318
B -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872
D -0.933237  0.955057  0.190794  1.978757

In [215]:
df.iloc[0]  #integer-based index notation
# type(df.iloc[0])    #pandas.core.series.Series

W    0.907969
X    0.503826
Y    0.651118
Z   -0.319318
Name: A, dtype: float64

**Selecting Rows**

In [216]:
df.loc['A'] #label-based index notation

W    0.907969
X    0.503826
Y    0.651118
Z   -0.319318
Name: A, dtype: float64

Or select based off of position instead of label 

In [217]:
# '.loc[]' and '.iloc[]' are just for grabbing rows not columns.

In [218]:
df.iloc[2] #the numerical index position. (even if our axes are labeled by strings.)
#Conclusion: Not only are all the columns Series but the rows are Series as well, as far as the way they're gonna get returned when we request them in Pandas.

W    0.528813
X   -0.589001
Y    0.188695
Z   -0.758872
Name: C, dtype: float64

In [219]:
df.loc['C']

W    0.528813
X   -0.589001
Y    0.188695
Z   -0.758872
Name: C, dtype: float64

In [220]:
# Pass a list of row names
df.loc[['C', 'B']]

W         X         Y         Z
C  0.528813 -0.589001  0.188695 -0.758872
B -0.848077  0.605965 -2.018168  0.740122

**Selecting subset of rows and columns**

In [221]:
df.loc['B','Y']

-2.018168244037392

In [222]:
round(df.loc['B','Y'], 2)

-2.02

In [223]:
df.loc[['A','B'],['W','Y']]

W         Y
A  0.907969  0.651118
B -0.848077 -2.018168

In [224]:
df.loc[['A','B']]

W         X         Y         Z
A  0.907969  0.503826  0.651118 -0.319318
B -0.848077  0.605965 -2.018168  0.740122

In [225]:
arr2d = np.array([[1, 2], [3, 4], [5, 6]])
print(arr2d)
print(arr2d[[0, 2]])  # Rows 0 and 2 → Output: [[1 2], [5 6]]


row_indices = [0, 1, 2]
col_indices = [1, 0, 1]
print(arr2d[row_indices, col_indices])  # Output: [2 3 6]
# This last one is like picking elements at positions (0,1), (1,0), and (2,1).

print(arr2d[0])


[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [5 6]]
[2 3 6]
[1 2]


In [226]:
print(arr2d[[0]])

[[1 2]]


### Conditional Selection

An important feature of pandas is conditional selection using bracket notation, very similar to numpy:

In [227]:
arr = np.array([10, 20, 30, 40, 50])

# Select elements greater than 25
condition = arr > 25
result = arr[condition]

print(condition, '\n', result)

[False False  True  True  True] 
 [30 40 50]


In [228]:
df

W         X         Y         Z
A  0.907969  0.503826  0.651118 -0.319318
B -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872
D -0.933237  0.955057  0.190794  1.978757
E  2.605967  0.683509  0.302665  1.693723

In [229]:
df>0    #We will get a DataFrame back of boolean values.

W      X      Y      Z
A   True   True   True  False
B  False   True  False   True
C   True  False   True  False
D  False   True   True   True
E   True   True   True   True

In [230]:
df[df>0]

W         X         Y         Z
A  0.907969  0.503826  0.651118       NaN
B       NaN  0.605965       NaN  0.740122
C  0.528813       NaN  0.188695       NaN
D       NaN  0.955057  0.190794  1.978757
E  2.605967  0.683509  0.302665  1.693723

In [231]:
df['W']>0

A     True
B    False
C     True
D    False
E     True
Name: W, dtype: bool

In [232]:
# df['W']>0   #we can now use this Series of boolean values corresponding to rows (one per row) to filter out rows based off of the values in column 'W'.
df[df['W']>0] #It will filter rows where column 'W' is greater than 0. In our case rows 'B' and 'D' won't get returned.
#df[df['W']>0]: Now because we're passing in a Series we don't get those NaN values anymore. We only get those NaN values when we're doing this sort of condition 'df[df>0]' on the entire DataFrame, but here we're passing in conditions based off of columns.

W         X         Y         Z
A  0.907969  0.503826  0.651118 -0.319318
C  0.528813 -0.589001  0.188695 -0.758872
E  2.605967  0.683509  0.302665  1.693723

In [233]:
df[df['W']>0]['Y']

A    0.651118
C    0.188695
E    0.302665
Name: Y, dtype: float64

In [234]:
df[df['W']>0].loc['A']

W    0.907969
X    0.503826
Y    0.651118
Z   -0.319318
Name: A, dtype: float64

In [235]:
# We want to grab all the rows in our DataFrame where 'Z' is less than zero:
df[df['Z']<0]

W         X         Y         Z
A  0.907969  0.503826  0.651118 -0.319318
C  0.528813 -0.589001  0.188695 -0.758872

In [236]:
df[df['W']>0][['Y','X']]

Y         X
A  0.651118  0.503826
C  0.188695 -0.589001
E  0.302665  0.683509

In [237]:
df.index

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [238]:
df.columns

Index(['W', 'X', 'Y', 'Z'], dtype='object')

In [239]:
# I want to filter columns where row 'A' is greater than zero:
# df.loc[:, df.loc['A']> 0]
'''
df.loc['A'] > 0
This returns a Boolean Series for each column based on whether row 'A' is greater than 0. To use this to filter the columns:
df.loc[:, df.loc['A'] > 0]
'''
df.loc[:, df.loc['A']> 0]

W         X         Y
A  0.907969  0.503826  0.651118
B -0.848077  0.605965 -2.018168
C  0.528813 -0.589001  0.188695
D -0.933237  0.955057  0.190794
E  2.605967  0.683509  0.302665

In [240]:
# I want to filter rows where column 'W' is greater than 0:
df[df['W'] > 0]


W         X         Y         Z
A  0.907969  0.503826  0.651118 -0.319318
C  0.528813 -0.589001  0.188695 -0.758872
E  2.605967  0.683509  0.302665  1.693723

For two (or multiple) conditions you can use | and & with parenthesis to separate each conditional selection statement:

In [241]:
#df[(df['W']>0) and (df['Y'] > 0)]  # ValueError. Python's normal 'and' operator got confused because it can't take into account a Series of boolean values compared to another Series of boolean values. 'and' operator can only take into account single booleans at a time like 'True and False' which returns 'False', 'True and True' which returns 'True', and 'False and False' which returns 'False'. So here we have to use &. The reason for using '|' instead of 'or' is the same.
df[(df['W']>0) & (df['Y'] > 0)] # & = and

W         X         Y         Z
A  0.907969  0.503826  0.651118 -0.319318
C  0.528813 -0.589001  0.188695 -0.758872
E  2.605967  0.683509  0.302665  1.693723

In [242]:
df[(df['W']>0) | (df['Y'] > 0)] # | = or

W         X         Y         Z
A  0.907969  0.503826  0.651118 -0.319318
C  0.528813 -0.589001  0.188695 -0.758872
D -0.933237  0.955057  0.190794  1.978757
E  2.605967  0.683509  0.302665  1.693723

In [243]:
df[(df['W']>0) & (df['Y'] > 1)]

Empty DataFrame
Columns: [W, X, Y, Z]
Index: []

In [244]:
df

W         X         Y         Z
A  0.907969  0.503826  0.651118 -0.319318
B -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872
D -0.933237  0.955057  0.190794  1.978757
E  2.605967  0.683509  0.302665  1.693723

In [245]:
df[df['W']>0]

W         X         Y         Z
A  0.907969  0.503826  0.651118 -0.319318
C  0.528813 -0.589001  0.188695 -0.758872
E  2.605967  0.683509  0.302665  1.693723

In [246]:
df[df['Y']>1]

Empty DataFrame
Columns: [W, X, Y, Z]
Index: []

## More Index Details

Let's discuss some more features of indexing, including resetting the index or setting it something else. We'll also talk about index hierarchy!

In [247]:
#df = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())
df

W         X         Y         Z
A  0.907969  0.503826  0.651118 -0.319318
B -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872
D -0.933237  0.955057  0.190794  1.978757
E  2.605967  0.683509  0.302665  1.693723

In [248]:
# Reset to default 0,1...n index
df.reset_index() # '.reset_index()' is just gonna reset your index to a numerical index (starting from 0) and take your old index and set it as a new column. So your previous (old) index gets reset and becomes a column. It doesn't occur in place unless we specify it.
# df.reset_index().shape    #(5,5)
#df.reset_index().columns   #Index(['index', 'W', 'X', 'Y', 'Z'], dtype='object')
#df.reset_index().index     #RangeIndex(start=0, stop=5, step=1)

index         W         X         Y         Z
0     A  0.907969  0.503826  0.651118 -0.319318
1     B -0.848077  0.605965 -2.018168  0.740122
2     C  0.528813 -0.589001  0.188695 -0.758872
3     D -0.933237  0.955057  0.190794  1.978757
4     E  2.605967  0.683509  0.302665  1.693723

In [249]:
df #as we said, the above cell doesn't occur in place and we still have that original index of labels.

W         X         Y         Z
A  0.907969  0.503826  0.651118 -0.319318
B -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872
D -0.933237  0.955057  0.190794  1.978757
E  2.605967  0.683509  0.302665  1.693723

In [250]:
newind = 'CA NY WY OR CO'.split()

In [251]:
df['States'] = newind

In [252]:
df

W         X         Y         Z States
A  0.907969  0.503826  0.651118 -0.319318     CA
B -0.848077  0.605965 -2.018168  0.740122     NY
C  0.528813 -0.589001  0.188695 -0.758872     WY
D -0.933237  0.955057  0.190794  1.978757     OR
E  2.605967  0.683509  0.302665  1.693723     CO

In [253]:
df.set_index('States')

W         X         Y         Z
States                                        
CA      0.907969  0.503826  0.651118 -0.319318
NY     -0.848077  0.605965 -2.018168  0.740122
WY      0.528813 -0.589001  0.188695 -0.758872
OR     -0.933237  0.955057  0.190794  1.978757
CO      2.605967  0.683509  0.302665  1.693723

In [254]:
df

W         X         Y         Z States
A  0.907969  0.503826  0.651118 -0.319318     CA
B -0.848077  0.605965 -2.018168  0.740122     NY
C  0.528813 -0.589001  0.188695 -0.758872     WY
D -0.933237  0.955057  0.190794  1.978757     OR
E  2.605967  0.683509  0.302665  1.693723     CO

In [255]:
df.set_index('States',inplace=True)

In [256]:
df

W         X         Y         Z
States                                        
CA      0.907969  0.503826  0.651118 -0.319318
NY     -0.848077  0.605965 -2.018168  0.740122
WY      0.528813 -0.589001  0.188695 -0.758872
OR     -0.933237  0.955057  0.190794  1.978757
CO      2.605967  0.683509  0.302665  1.693723

## Multi-Index and Index Hierarchy

Let us go over how to work with Multi-Index, first we'll create a quick example of what a Multi-Indexed DataFrame would look like:

In [284]:
# Index Levels
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside)) #This zips them into pairs (tuple pairs) and gives:  [('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]
# Create a MultiIndex from Tuples:
hier_index = pd.MultiIndex.from_tuples(hier_index)  # It takes a list (like the one above made of tuples) and creates a MultiIndex object from it.
'''
This tells Pandas:
    "Take these pairs and treat them as multi-level index entries."
So the resulting hier_index is a Pandas MultiIndex object with two levels:
    Level 0: 'G1', 'G2'
    Level 1: 1, 2, 3 (nested within each 'G1' and 'G2')
''';

In [258]:
hier_index
# type(hier_index)

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [259]:
hier_index.levels

FrozenList([['G1', 'G2'], [1, 2, 3]])

In [260]:
hier_index.levels[0]

Index(['G1', 'G2'], dtype='object')

In [261]:
df = pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])
df  #It's a DataFrame with multi-levels of an index (index hierarchy).

A         B
G1 1 -1.136645  0.000366
   2  1.025984 -0.156598
   3 -0.031579  0.649826
G2 1  2.154846 -0.610259
   2 -0.755325 -0.346419
   3  0.147027 -0.479448

In [262]:
df.index.names  #our indices don't have any names!

FrozenList([None, None])

Now let's show how to index this! For index hierarchy we use df.loc[], if this was on the columns axis, you would just use normal bracket notation df[]. Calling one level of the index returns the sub-dataframe:

In [263]:
df.loc['G1']

A         B
1 -1.136645  0.000366
2  1.025984 -0.156598
3 -0.031579  0.649826

In [264]:
df.loc['G1'].loc[1]

A   -1.136645
B    0.000366
Name: 1, dtype: float64

In [265]:
df.index.names

FrozenList([None, None])

In [266]:
df.index.names = ['Group','Num']

In [267]:
df
#df: In your DataFrame df, you have a MultiIndex on the rows, where the index is composed of two levels: 'Group' and 'Num'.
# df.shape  (6, 2)

A         B
Group Num                    
G1    1   -1.136645  0.000366
      2    1.025984 -0.156598
      3   -0.031579  0.649826
G2    1    2.154846 -0.610259
      2   -0.755325 -0.346419
      3    0.147027 -0.479448

In [268]:
type(df.index)

pandas.core.indexes.multi.MultiIndex

In [269]:
df.loc['G1']

A         B
Num                    
1   -1.136645  0.000366
2    1.025984 -0.156598
3   -0.031579  0.649826

In [270]:
df.loc['G1'].loc[1]

A   -1.136645
B    0.000366
Name: 1, dtype: float64

In [271]:
df.loc[('G1',1)]

A   -1.136645
B    0.000366
Name: (G1, 1), dtype: float64

In [272]:
df.loc['G1'].loc[1]['B']

0.000366479605643592

In [273]:
df.loc['G1'].loc[(1, 'B')]

0.000366479605643592

In [274]:
df.loc['G1'].loc[1,'B']

0.000366479605643592

In [275]:
df.loc[('G1', 1), 'B']

0.000366479605643592

In [276]:
# We want to grab everything that was under 'G1'
df.xs('G1') #The method df.xs() stands for "cross section", and it's used to select data at a particular level of a MultiIndex.
#.shape (3, 2)

A         B
Num                    
1   -1.136645  0.000366
2    1.025984 -0.156598
3   -0.031579  0.649826

In [277]:
# df.xs('G1')
# Or
df.loc['G1']

A         B
Num                    
1   -1.136645  0.000366
2    1.025984 -0.156598
3   -0.031579  0.649826

In [278]:
df.xs(('G1',1))

A   -1.136645
B    0.000366
Name: (G1, 1), dtype: float64

In [279]:
df.xs(1,level='Num')    #we want all values where 'Num', the inside index, is equal to 1.
'''
It means:

"Give me all rows where the 'Num' level is 1, across all 'Group' values." It collapses the 'Num' level and keeps 'Group' as the index. 
'''

'\nIt means:\n\n"Give me all rows where the \'Num\' level is 1, across all \'Group\' values." It collapses the \'Num\' level and keeps \'Group\' as the index. \n'

In [280]:
# df.xs(1,level='Num')
#Or
df.loc[(slice(None), 1), :].reset_index('Num', drop=True)

A         B
Group                    
G1    -1.136645  0.000366
G2     2.154846 -0.610259

In [281]:
df.loc[('G1', 1), 'A']

-1.1366445936091856

In [282]:
print(df.loc[(slice(None), 1), :])
'''
This is saying:
    “Give me all rows where the MultiIndex is (any Group, Num == 1)”
slice(None) means "all values" (for the first index level, which is 'Group')
1 is the second index level value ('Num')
: selects all columns
''';

                  A         B
Group Num                    
G1    1   -1.136645  0.000366
G2    1    2.154846 -0.610259


In [283]:
df.loc[(slice(None), 1), :].reset_index('Num', drop = True)

A         B
Group                    
G1    -1.136645  0.000366
G2     2.154846 -0.610259

# Great Job!